// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Connection struct {
	ID           uuid.UUID `json:"id"`
	WorkflowID   uuid.UUID `json:"workflowId"`
	SourceNodeID uuid.UUID `json:"sourceNodeId"`
	TargetNodeID uuid.UUID `json:"targetNodeId"`
	FromOutput   string    `json:"fromOutput"`
	ToInput      string    `json:"toInput"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Node struct {
	ID         uuid.UUID       `json:"id"`
	WorkflowID uuid.UUID       `json:"workflowId"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	Position   json.RawMessage `json:"position"`
	Data       json.RawMessage `json:"data"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  time.Time       `json:"updatedAt"`
}

type Workflow struct {
	ID          uuid.UUID `json:"id"`
	UserID      string    `json:"userId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}
