// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"encoding/json"
	"time"
)

type Connection struct {
	ID           int32     `json:"id"`
	WorkflowID   int32     `json:"workflowId"`
	SourceNodeID int32     `json:"sourceNodeId"`
	TargetNodeID int32     `json:"targetNodeId"`
	FromOutput   string    `json:"fromOutput"`
	ToInput      string    `json:"toInput"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Node struct {
	ID         int32           `json:"id"`
	WorkflowID int32           `json:"workflowId"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	Position   json.RawMessage `json:"position"`
	Data       json.RawMessage `json:"data"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  time.Time       `json:"updatedAt"`
}

type Workflow struct {
	ID          int32     `json:"id"`
	UserID      string    `json:"userId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}
